FROM --platform=linux/amd64 python:3.8-slim

WORKDIR /app

RUN pip install psutil
RUN pip install tld

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt && pip list

COPY . /app/

CMD sh -c "PYTHONPATH=$(pwd) celery -A celery_config.app worker --loglevel=info -E --pool=solo & python -m http.server 5000"
